Others: {Hmax: 255, Hmin: 0, Smax: 255, Smin: 0, Vmax: 255, Vmin: 0}
RedTarget: {Hmax: 255, Hmin: 106, Smax: 255, Smin: 115, Vmax: 255, Vmin: 0}
YellowTarget: {Hmax: 110, Hmin: 58, Smax: 255, Smin: 115, Vmax: 255, Vmin: 0}
