Others: {Hmax: 255, Hmin: 0, Smax: 255, Smin: 0, Vmax: 255, Vmin: 0}
RedTarget: {Hmax: 255, Hmin: 106, Smax: 255, Smin: 125, Vmax: 255, Vmin: 123}
YellowTarget: {Hmax: 110, Hmin: 78, Smax: 162, Smin: 48, Vmax: 255, Vmin: 220}
